name: xiaoheiqun
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jpush_flutter: ^0.0.13
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.2.7
  fluwx: ^0.6.3
  umeng_uapp: ^1.0.3
  dio: ^2.1.7
  toast: ^0.1.4
  image_picker: ^0.4.5
  json_serializable: ^2.0.0
  build_runner: ^1.1.2
  oktoast: ^ 2.1.9
  shared_preferences: ^0.5.1
  flutter_cache_manager: ^1.1.0
  cached_network_image: ^1.1.0
  package_info: ^0.3.2
  url_launcher: ^5.0.2
  flutter_easyrefresh: ^1.2.7
  flutter_localizations:
    sdk: flutter
  path_provider: ^1.2.0
  flutter_cupertino_date_picker: ^1.0.8
  crypto: ^2.0.6
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  event_bus: ^1.1.0

  #  flutter_webview_plugin: ^0.3.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image/banner1.png
    - image/banner2.png
    - image/index_book.png
    - image/index_book_select.png
    - image/index_home.png
    - image/index_home_select.png
    - image/index_share.png
    - image/index_share_select.png
    - image/index_card.png
    - image/index_card_select.png
    - image/tianjiatupian.png
    - image/liulan@2x.png
    - image/welcome.png
    - image/shijian@2x.png
    - image/img1.png
    - image/age@2x.png
    - image/path_8@2x.png
    - image/nologin@2x.png
    - image/female@2x.png
    - image/vip@2x.png
    - image/shape_copy2@2x.png
    - image/shoucang1.png
    - image/liaotian.png
    - image/back@2x.png
    - image/shoucang2.png
    - image/sel_@2x_290.png
    - image/sel_@2x_294.png
    - image/logo@2x.png
    - image/male@2x.png
    - image/download.png
    - image/img5.png
    - image/line_copy23@2x.png
    - image/shoucang3.png
    - image/vipicon.png
    - image/renzheng.png
    - image/kefu@2x.png
    - image/upload@2x.png
    - image/biaoqian.png
    - image/vip_copy4@2x.png
    - image/talk@2x.png
    - image/weipay@2x.png
    - image/fabu_btn.png
    - image/huangguan.png
    - image/del@2x.png
    - image/app_advert.jpg
    - image/finish@2x.png
    - image/oval_2@2x.png
    - image/VIP_blank.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Arial
       fonts:
         - asset: fonts/Arial.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
